import 'models/travel_service_model.dart';

final List<TravelService> mockTravelServices = [
  // ---------------- HOTELS ----------------
  const TravelService(
    id: 'svc_h1',
    name: 'Serena Mountain Resort',
    category: 'Hotels',
    location: 'Hunza, Pakistan',
    description:
    'A luxury mountain resort offering breathtaking views of the Karakoram range, with spacious rooms and warm hospitality.',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
    rating: 4.8,
    price: 18000,
    priceUnit: 'per night',
    features: ['Free Wi-Fi', 'Breakfast included', 'Parking', 'Mountain view', '24/7 reception'],
  ),
  const TravelService(
    id: 'svc_h2',
    name: 'Luxus Grand Hotel',
    category: 'Hotels',
    location: 'Skardu, Pakistan',
    description: 'A modern hotel in the heart of Skardu, perfect for travelers exploring the northern valleys.',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa',
    rating: 4.5,
    price: 14000,
    priceUnit: 'per night',
    features: ['Free Wi-Fi', 'Restaurant', 'Parking', '24/7 reception'],
  ),
  const TravelService(
    id: 'svc_h3',
    name: 'Pearl Continental Murree',
    category: 'Hotels',
    location: 'Murree, Pakistan',
    description: 'A classic hilltop hotel with panoramic pine-forest views, close to Mall Road.',
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4',
    rating: 4.3,
    price: 12000,
    priceUnit: 'per night',
    features: ['Free Wi-Fi', 'Breakfast included', 'Heating', 'Room service'],
  ),
  const TravelService(
    id: 'svc_h4',
    name: 'Naran View Cottages',
    category: 'Hotels',
    location: 'Naran, Pakistan',
    description: 'Cozy riverside cottages with unobstructed views of the Kunhar River.',
    imageUrl: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8',
    rating: 4.2,
    price: 9000,
    priceUnit: 'per night',
    features: ['River view', 'Bonfire area', 'Parking', 'Breakfast included'],
  ),
  const TravelService(
    id: 'svc_h5',
    name: 'Swat Serena Hotel',
    category: 'Hotels',
    location: 'Swat, Pakistan',
    description: 'A serene retreat surrounded by orchards and mountains in the Switzerland of Pakistan.',
    imageUrl: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
    rating: 4.6,
    price: 15500,
    priceUnit: 'per night',
    features: ['Free Wi-Fi', 'Garden view', 'Breakfast included', 'Parking'],
  ),

  // ---------------- TOURS ----------------
  const TravelService(
    id: 'svc_t1',
    name: 'Hunza Valley Explorer',
    category: 'Tours',
    location: 'Hunza, Pakistan',
    description: '3-day guided tour through Karimabad, Attabad Lake, and Passu Cones.',
    imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3',
    rating: 4.9,
    price: 22000,
    priceUnit: 'per person',
    features: ['Professional guide', 'Transportation', 'Meals', 'Sightseeing'],
  ),
  const TravelService(
    id: 'svc_t2',
    name: 'Skardu Adventure Tour',
    category: 'Tours',
    location: 'Skardu, Pakistan',
    description: 'Explore Shangrila Resort, Upper Kachura Lake, and Deosai plains on this multi-day tour.',
    imageUrl: 'https://images.unsplash.com/photo-1580500550469-c8b0e4b6b3b8',
    rating: 4.7,
    price: 25000,
    priceUnit: 'per person',
    features: ['Professional guide', 'Transportation', 'Meals', 'Sightseeing'],
  ),
  const TravelService(
    id: 'svc_t3',
    name: 'Fairy Meadows Trek',
    category: 'Tours',
    location: 'Fairy Meadows, Pakistan',
    description: 'Trek to the base camp views of Nanga Parbat, the ninth-highest mountain in the world.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
    rating: 4.8,
    price: 20000,
    priceUnit: 'per person',
    features: ['Professional guide', 'Camping gear', 'Meals', 'Porters'],
  ),
  const TravelService(
    id: 'svc_t4',
    name: 'Swat Cultural Heritage Tour',
    category: 'Tours',
    location: 'Swat, Pakistan',
    description: 'Visit Mingora, ancient Buddhist ruins, and the Malam Jabba ski resort.',
    imageUrl: 'https://images.unsplash.com/photo-1500534623283-312aade485b7',
    rating: 4.4,
    price: 16000,
    priceUnit: 'per person',
    features: ['Professional guide', 'Transportation', 'Sightseeing'],
  ),
  const TravelService(
    id: 'svc_t5',
    name: 'Islamabad City Tour',
    category: 'Tours',
    location: 'Islamabad, Pakistan',
    description: 'A day tour covering Faisal Mosque, Daman-e-Koh, and Lok Virsa Museum.',
    imageUrl: 'https://images.unsplash.com/photo-1591370874773-6702e8f12fd8',
    rating: 4.3,
    price: 6000,
    priceUnit: 'per person',
    features: ['Professional guide', 'Transportation', 'Entry tickets'],
  ),

  // ---------------- TRANSPORTATION ----------------
  const TravelService(
    id: 'svc_tr1',
    name: 'Private SUV Transfer',
    category: 'Transportation',
    location: 'Islamabad → Hunza',
    description: 'Comfortable private SUV transfer along the Karakoram Highway with an experienced driver.',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf',
    rating: 4.6,
    price: 35000,
    priceUnit: 'per trip',
    features: ['Air conditioning', 'Professional driver', 'Luggage included'],
  ),
  const TravelService(
    id: 'svc_tr2',
    name: 'Skardu Airport Transfer',
    category: 'Transportation',
    location: 'Skardu, Pakistan',
    description: 'Reliable airport pickup and drop-off service to your hotel in Skardu.',
    imageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d',
    rating: 4.4,
    price: 4000,
    priceUnit: 'per trip',
    features: ['Air conditioning', 'Professional driver', 'Luggage included'],
  ),
  const TravelService(
    id: 'svc_tr3',
    name: 'Private Mountain Jeep',
    category: 'Transportation',
    location: 'Naran, Pakistan',
    description: '4x4 jeep hire for rough mountain terrain, ideal for Saif-ul-Malook and Babusar Top.',
    imageUrl: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c',
    rating: 4.5,
    price: 8000,
    priceUnit: 'per trip',
    features: ['4x4 vehicle', 'Professional driver', 'Fuel included'],
  ),
  const TravelService(
    id: 'svc_tr4',
    name: 'Murree Hills Shuttle',
    category: 'Transportation',
    location: 'Islamabad → Murree',
    description: 'Comfortable shuttle service running between Islamabad and Murree.',
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000',
    rating: 4.1,
    price: 3000,
    priceUnit: 'per trip',
    features: ['Air conditioning', 'Fixed schedule', 'Affordable'],
  ),
  const TravelService(
    id: 'svc_tr5',
    name: 'Swat Valley Coaster',
    category: 'Transportation',
    location: 'Islamabad → Swat',
    description: 'Group coaster transport ideal for families and small tour groups.',
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a',
    rating: 4.2,
    price: 5000,
    priceUnit: 'per trip',
    features: ['Air conditioning', 'Spacious seating', 'Luggage included'],
  ),

  // ---------------- ACTIVITIES ----------------
  const TravelService(
    id: 'svc_a1',
    name: 'Attabad Lake Adventure',
    category: 'Activities',
    location: 'Hunza, Pakistan',
    description: 'Boating and jet-skiing on the turquoise waters of Attabad Lake.',
    imageUrl: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21',
    rating: 4.7,
    price: 3500,
    priceUnit: 'per person',
    features: ['Safety equipment', 'Professional instructor', 'Insurance'],
  ),
  const TravelService(
    id: 'svc_a2',
    name: 'River Rafting — Skardu',
    category: 'Activities',
    location: 'Skardu, Pakistan',
    description: 'White-water rafting on the Indus River with certified safety guides.',
    imageUrl: 'https://images.unsplash.com/photo-1530866495561-507c9faab8f8',
    rating: 4.6,
    price: 5000,
    priceUnit: 'per person',
    features: ['Safety equipment', 'Professional instructor', 'Insurance'],
  ),
  const TravelService(
    id: 'svc_a3',
    name: 'Jeep Safari — Deosai Plains',
    category: 'Activities',
    location: 'Deosai, Pakistan',
    description: 'An off-road jeep safari across the "Land of Giants," home to the Himalayan brown bear.',
    imageUrl: 'https://images.unsplash.com/photo-1533130061792-64b345e4a833',
    rating: 4.8,
    price: 7000,
    priceUnit: 'per person',
    features: ['4x4 vehicle', 'Professional guide', 'Wildlife spotting'],
  ),
  const TravelService(
    id: 'svc_a4',
    name: 'Cultural Village Tour — Hunza',
    category: 'Activities',
    location: 'Hunza, Pakistan',
    description: 'Walk through traditional Hunza villages, meet locals, and taste authentic cuisine.',
    imageUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04',
    rating: 4.5,
    price: 2500,
    priceUnit: 'per person',
    features: ['Local guide', 'Traditional meal', 'Cultural insights'],
  ),
  const TravelService(
    id: 'svc_a5',
    name: 'Paragliding — Malam Jabba',
    category: 'Activities',
    location: 'Swat, Pakistan',
    description: 'Tandem paragliding over the green hills of Malam Jabba with certified pilots.',
    imageUrl: 'https://images.unsplash.com/photo-1517090504586-fde19ea6066f',
    rating: 4.9,
    price: 9000,
    priceUnit: 'per person',
    features: ['Safety equipment', 'Certified pilot', 'Insurance'],
  ),
];